name: build-metrics
run-name: ${{ github.actor }} ran build-metrics
on: [push]
jobs:
  run-build-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: python3 -m pip install bokeh mako
      - run: python3 build_metrics.py --strict_errors
